# version: '3.8'

services:
  # Database
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    ports:
      - "3306:3306"
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: '${MARIADB_ROOT_PASSWORD}'
      MARIADB_DATABASE: '${MARIADB_DATABASE}'
      MARIADB_USER: '${MARIADB_USER}'
      MARIADB_PASSWORD: '${MARIADB_PASSWORD}'
    networks:
      - inception 
    restart: on-failure

  wordpress:
    container_name: wordpress
    depends_on:
    - mariadb
    build: ./requirements/wordpress/
    volumes:      
      - wordpress_volume:/var/www/wordpress   
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: '${WORDPRESS_DB_HOST}'
      WORDPRESS_DB_NAME: '${WORDPRESS_DB_NAME}'
      WORDPRESS_DB_USER: '${WORDPRESS_DB_USER}'
      WORDPRESS_DB_PASSWORD: '${WORDPRESS_DB_PASSWORD}'
      WP_TITLE: '${WP_TITLE}'
      WP_ADMIN: '${WP_ADMIN}'
      WP_ADMIN_PASSWD: '${WP_ADMIN_PASSWD}'
      WP_ADMIN_MAIL: '${WP_ADMIN_MAIL}'
      WP_USER: '${WP_USER}'
      WP_USER_MAIL: '${WP_USER_MAIL}'
      WP_USER_PASSWD: '${WP_USER_PASSWD}'
      DOMAIN_NAME: '${DOMAIN_NAME}'
    networks:
      - inception 
    ports:
      - "9000:9000"
    restart: always

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    volumes:      
      - wordpress_volume:/var/www/wordpress
    env_file: .env
    environment:
      DOMAIN_NAME: '${DOMAIN_NAME}'
    networks:
      - inception 
    ports:
      - "443:443"
    restart: always


#Network

networks:
  inception:
    name: inception
    driver: bridge

#Volumes

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/matle-br/data/mariadb

  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/matle-br/data/wordpress

