# version: '3.8'

services:
  # Database
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    stdin_open: true
    tty: true
    expose:
      - '3306'
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - myNetwork 
    restart: always


  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    depends_on:
      - wordpress
    stdin_open: true
    tty: true
    networks:
      - myNetwork 
    ports:
      - "443:443"
    links:
      - wordpress
    restart: always

  
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress/
    stdin_open: true
    tty: true
    volumes:      
      - wordpress_volume:/var/www/html
    env_file:
      - .env
    networks:
      - myNetwork 
    expose:
      - "9000"
    links:
      - mariadb
    restart: always

#Network

networks:
  myNetwork:
    driver: bridge

#Volumes

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/matle-br/data/mariadb'

  wordpress_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/matle-br/data/wordpress'

