# version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    ports:
      - "3306:3306"
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: '${MARIADB_ROOT_PASSWORD}'
      MARIADB_DATABASE: '${MARIADB_DATABASE}'
      MARIADB_USER: '${MARIADB_USER}'
      MARIADB_PASSWORD: '${MARIADB_PASSWORD}'
    networks:
      - inception 
    restart: on-failure

  wordpress:
    container_name: wordpress
    depends_on:
    - mariadb
    build: ./requirements/wordpress/
    volumes:      
      - wordpress_volume:/var/www/wordpress   
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: '${WORDPRESS_DB_HOST}'
      WORDPRESS_DB_NAME: '${WORDPRESS_DB_NAME}'
      WORDPRESS_DB_USER: '${WORDPRESS_DB_USER}'
      WORDPRESS_DB_PASSWORD: '${WORDPRESS_DB_PASSWORD}'
      WP_TITLE: '${WP_TITLE}'
      WP_ADMIN: '${WP_ADMIN}'
      WP_ADMIN_PASSWD: '${WP_ADMIN_PASSWD}'
      WP_ADMIN_MAIL: '${WP_ADMIN_MAIL}'
      WP_USER: '${WP_USER}'
      WP_USER_MAIL: '${WP_USER_MAIL}'
      WP_USER_PASSWD: '${WP_USER_PASSWD}'
      DOMAIN_NAME: '${DOMAIN_NAME}'
    networks:
      - inception 
    ports:
      - "9000:9000"
    restart: always

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
      - static_page
    build: ./requirements/nginx/
    volumes:      
      - wordpress_volume:/var/www/wordpress
      - website_volume:/var/www/home
    env_file: .env
    environment:
      DOMAIN_NAME: '${DOMAIN_NAME}'
    networks:
      - inception 
    ports:
      - "443:443"
      - "4242:4242"
    restart: always
  
  #Bonus

  static_page:
    container_name: static_page
    build: ./requirements/bonus/static_page/
    networks:
      - inception
    volumes:      
      - website_volume:/var/www/home
    restart: on-failure

  redis:
    container_name: redis
    depends_on:
      - mariadb
    build: ./requirements/bonus/redis/
    networks:
      - inception
    ports:
      - "6379:6379"
    restart: always

  adminer:
    container_name: adminer
    depends_on:
      - wordpress
    build: ./requirements/bonus/adminer
    volumes:      
      - wordpress_volume:/var/www/wordpress
    networks:
      - inception
    restart: on-failure

  ftp:
    container_name: ftp
    depends_on:
      - wordpress
    build: ./requirements/bonus/ftp
    env_file: .env
    environment:
      FTP_USERNAME: '${FTP_USERNAME}'
      FTP_PASSWORD: '${FTP_PASSWORD}'
    volumes:      
      - wordpress_volume:/home/ftpuser/ftp/files
    networks:
      - inception
    ports:
      - "20:20"
      - "21:21"
      - "40000-40005:40000-40005"
    restart: on-failure

  portainer:
    container_name: portainer
    build: ./requirements/bonus/portainer
    networks:
      - inception
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9443:9443"
    restart: always

#Network

networks:
  inception:
    name: inception
    driver: bridge

#Volumes

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/matle-br/data/mariadb

  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/matle-br/data/wordpress

  website_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/matle-br/data/website
  
  portainer_data:

